### NumPy
##### NumPy(Numerical Python) is an open source Python library that aids in mathematical, scientific, engineering, and data science programming.

##### NumPy is the fundamental package for scientific computing with Python. it contains:

##### * a powerful N-dimensional array object
##### * extension package to Python for multidimensional arrays
##### * designed for scientific computation -- liner algebra, Fourier transform, and random number capabilities.
##### * NumPy can also be used as an efficient multi-dimensional container of generic data.
##### * This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.
##### * NumPy is an incredible library to perform mathematical and statistical operations because it is fast and memory efficient. closer to hardware (efficiency)

In [2]:
# Load in NumPy (Import NumPy Package)
import numpy as np

### ndarray object

##### The most important object defined in NumPy is an N-dimensional array type called ndarray. it describes the collection of items of the same type. items in the collection can be accessed using a zero-based index. Each element in ndarray is an object of datatype object (called dtype).
##### The basic ndarray is created using an array function in Numpy as follows:
##### numpy . array(object, dtype = None)
##### NOTE: In NumPy, axis = 0 is cols and axis = 1 is rows

In [5]:
a=[1,2,3,4,5]

In [6]:
print(a)

[1, 2, 3, 4, 5]


print(type(a))

In [8]:
np_a = np.array(a)

In [9]:
print(np_a)

[1 2 3 4 5]


In [7]:
print(type(np_a))

<class 'numpy.ndarray'>


##### why it is useful: Memory-efficient container that provides fast numerical operations.

In [10]:
#python lists 
L = range(1000)
%timeit [i**2 for i in L]

112 µs ± 3.62 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [10]:
a = np.arange(1000)
%timeit a**2

1.92 µs ± 20.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Creating arrays (Manually creating arrays)

In [11]:
#1-D
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [12]:
# print dimension
a.ndim

1

In [13]:
#shape
a.shape

(4,)

In [14]:
#2-D
b = np.array([[0,1,2], [3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
b.ndim

2

In [16]:
b.shape

(2, 3)

In [14]:
#3D
c = np.array([[[0,1], [2,3]], [[4,5], [6,7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [18]:
c.ndim

3

In [19]:
c.shape

(2, 2, 2)

### Creating NumPy Arrays From a List

In [15]:
# we know how to create a list, right
my_list = [1,2,3]
my_list

[1, 2, 3]

In [21]:
np.array(my_list)

array([1, 2, 3])

In [17]:
# we can convert a matrix which is also a list to array
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.array(my_matrix).shape

(3, 3)

### Function for creating arrays

##### A new ndarray object can be created by any of the following array creation routines:

##### . list_nparray = np.array(python_list,dtype)
##### . arange_array = np.arange(start,end,step,dtype)
##### . zero_array = np.zeros(shape,dtype)
##### . ones_array = np.ones(shape,dtype)
##### . linespace_array = np.linespace(start_element, end_element, num_of_elements)
##### . empty_array = np.empty(shape,dtype)
##### . random_array = np.random.randint(start,end,num_elements)

### arange
##### which will return evenly spaced values within agiven interval.

In [20]:
# using arange function --> arange is an array-valued version of the built-in python range function
a = np.arange(10) # 0.....n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
b = np.arange(1,10,2) #start, end(exclusive), step
b

array([1, 3, 5, 7, 9])

### Linespace
##### Return evenly spaced numbers over a specified interval.

In [23]:
# using linspace
a = np.linspace(0,5,6) #start, end, nuber of points
a

array([0., 1., 2., 3., 4., 5.])

In [24]:
# I want to get 3 evenly spaced points between 0 to 10
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

### Zero and Ones

##### . Genrate arrays of zeros or ones

In [3]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
b = np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [6]:
a = np.ones((4,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Eye --> Create an identity matrix

##### . An indentity matrix if you are not familar is used in used in linear algebra problems and is a two dimentional squared matrix means number of rows are same as columns with diagonals of ones and everything is zero

In [7]:
c = np.eye(3) # Return a 2-D array with ones on the diagonal and zeros elsewhere.
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
d = np.eye(3,2) #3 is number of rows, 2 is number of columns, index of diagonal start with 0
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [9]:
# create array using diag function
a = np.diag([7,9,3,4])
a

array([[7, 0, 0, 0],
       [0, 9, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [10]:
np.diag(a)  #Extract diagonal

array([7, 9, 3, 4])

### random --> Numpy also has lots of ways to create random number arrays:

In [11]:
#randint -- Return random integers from start (inclusive) to end (exclusive).
random_array = np.random.randint(1,121,5)
print(random_array)

[107  74  54 113 113]


In [12]:
# rand -- Create an array of the given shape and populate it with random samples from a uniform distribution over [0,1]
a = np.random.rand(4)
a

array([0.06803281, 0.56697894, 0.26967113, 0.38827602])

In [13]:
#randn -- Return a sample (or samples) from the "standard normal" distribution. ***Gausian***
a = np.random.randn(100)
a

array([-0.17415371, -1.52255827,  0.86858969,  0.99234137,  0.04406265,
        0.64180984, -1.27024607,  0.51775785, -0.47989619, -1.25373387,
        1.38182999,  1.75654285,  0.53002114, -0.76685148,  0.3271134 ,
       -0.56697246,  0.32737968,  0.67448694,  0.10810613, -0.07234252,
        1.27247987,  0.90964663, -1.70013994, -1.36091706,  0.26256339,
       -2.22386506, -2.39612103, -0.09630701,  0.26530472, -0.5653882 ,
        1.98581502,  0.48710138,  0.60777816, -1.07552578,  1.5223981 ,
        1.78760759,  0.58843627, -0.04995584,  0.73830454, -0.06603023,
        0.61385084, -1.94716057,  1.70141595, -0.0751254 ,  0.02131501,
       -1.33739547, -0.93672043,  0.46186695, -0.70896664,  0.55341699,
       -1.38279532, -0.38132427, -0.20881791, -0.72358282,  0.05920218,
       -0.19943993,  0.85582375,  2.36294492, -0.4344182 ,  1.71551775,
       -0.35660629, -0.32043093, -0.24658346, -0.5525349 ,  0.08456873,
        1.5373653 ,  0.44659685, -0.03906339,  0.93611145,  1.35

### Copy array

In [14]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


### Reshape array

In [15]:
arr = np.arange(25)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)


In [16]:
# Notice the two sets of brackets
a1 = arr.reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print("Shape of a: {}".format(a.shape))

[[1 2 3]
 [4 5 6]]
Shape of a: (2, 3)


In [18]:
# reshaping
b = a.reshape(3,2)
print(b)
print("Shape of  b: {}".format(b.shape))

[[1 2]
 [3 4]
 [5 6]]
Shape of  b: (3, 2)


### Transpose array

In [2]:
a = np.array([[1,2,3],[4,5,6]])
print("Shape: {}".format(a.shape))
print(a)

Shape: (2, 3)
[[1 2 3]
 [4 5 6]]


In [3]:
c = a.T
print(c)

[[1 4]
 [2 5]
 [3 6]]


### Flattening

In [5]:
a = np.array([[1,2,3], [4,5,6]])
a.ravel() # Return a contiguous falttened array. A 1-D array, conatning the elements of the input, is returned. A copy is made only if needed.

array([1, 2, 3, 4, 5, 6])

In [6]:
c.ravel()

array([1, 4, 2, 5, 3, 6])

### Sorting

In [7]:
#Sorting along an axis:
# axis=1 --> row and axis=0 -->column
a = np.array([[5,4,6], [2,8,7]])
b = np.sort(a, axis=1)
b

array([[4, 5, 6],
       [2, 7, 8]])

### Add/Remove operations on a numpy array

In [8]:
a = np.array([4,6,7])
a = np.append(a,[3,5,4])
print('Numpy array after addition:' ,a)

Numpy array after addition: [4 6 7 3 5 4]


In [9]:
a = np.delete(a,2)
print('Numpy array after deletion of one element:',a)

Numpy array after deletion of one element: [4 6 3 5 4]


### Indexing 

##### The items of an array can be accessed and assigned to the same way as other Python sequences :

In [11]:
a = np.arange(3,10)
print(a)
print(a[5])

[3 4 5 6 7 8 9]
8


In [18]:
# for multidimensional arrays, indexes are tuples of intergers:
a = np.diag([1,2,3])
print(a)
print(a[2,1])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
0


In [19]:
a[2,1] = 4 #assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 4, 3]])

 ### Slicing

In [21]:
a = np.arange(4,20)
a

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
a[1:6:2] # [startindex: endindex(exclusive) : step]

array([5, 7, 9])

In [23]:
#we can also combine assignment and slicing:
a = np.arange(10)
a[5:]

array([5, 6, 7, 8, 9])

In [25]:
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [26]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [27]:
b[::-1]

array([4, 3, 2, 1, 0])

In [28]:
a[5:]=b[::-1]

In [29]:
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

### Fancy Indexing
##### NumPy arrays can be indexed with slices, but also with boolean or integer arrays (masks). This method is called fancy indexing.it creates copies not views.

In [3]:
a = np.random.randint(0,20,5)
a

array([ 8, 11, 13,  9, 16])

In [4]:
a[a % 2 == 0]

array([ 8, 16])

In [5]:
a[a % 2 == 0] = -1
a

array([-1, 11, 13,  9, -1])

### Indexing with an array of integers

In [7]:
a = np.arange(0,101,10)
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [8]:
#Indexing can be done with an array of integers, where the same index is repeated several time:
a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [9]:
#New values can be assigned
a[[9, 7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200,  100])

## Operations

### 1. Basic operations 
### with scalars

In [10]:
a = np.array([1, 2, 3, 4]) #create an array
print(a)
print(a+1)

[1 2 3 4]
[2 3 4 5]


In [11]:
a ** 2

array([ 1,  4,  9, 16])

### All arithmetic operates elementwise

In [12]:
b = np.ones(4) + 1
b

array([2., 2., 2., 2.])

In [13]:
a - b

array([-1.,  0.,  1.,  2.])

In [14]:
a * b

array([2., 4., 6., 8.])

In [15]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[4,4],[4,4],[4,4]])

#Adding a and b
print('Sum of a and b :\n', a+b)

Sum of a and b :
 [[ 5  6]
 [ 7  8]
 [ 9 10]]


In [16]:
# multilply a and b - elementwise multiplication
print('Product of a and b :\n', a*b)

Product of a and b :
 [[ 4  8]
 [12 16]
 [20 24]]


In [18]:
# Array multiplication
c =  np.diag([1,2,3,4])
print(c * c)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [19]:
# matrix multiplication
a = np.array([[1,2,1],[3,4,3],[5,6,5]])
b = np.array([[4,4,1],[4,4,2],[4,4,3]])
print(' Matrix Multiplication: \n', np.matmul(a,b))

 Matrix Multiplication: 
 [[16 16  8]
 [40 40 20]
 [64 64 32]]


### Comparisions

In [21]:
a = np.array([1,2,3,4])
b = np.array([5,3,3,4])
a == b

array([False, False,  True,  True])

In [22]:
a > b

array([False, False, False, False])

In [23]:
# Array-wise comparisions
a = np.array([1,2,3,4])
b = np.array([5,3,3,4])
c = np.array([1,2,3,4])

In [24]:
np.array_equal(a,b)

False

In [25]:
np.array_equal(a,b)

False

In [26]:
np.array_equal(a,c)

True

### Logical Operations

In [28]:
a = np.array([1,1,0,0], dtype=bool)
b = np.array([1,0,1,0], dtype=bool)

np.logical_or(a,b)

array([ True,  True,  True, False])

In [29]:
np.logical_and(a,b)

array([ True, False, False, False])

### Transcendental functions:

In [30]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [31]:
np.log(a)

C:\Users\Subrat Jena\AppData\Local\Temp\ipykernel_2524\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [32]:
np.exp(a)  #evaluates e^x for each element in a given input

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

### Shape Mismatch

In [34]:
a = np.arange(4)
a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

## Basic Reductions
### Computing Sums

In [35]:
x = np.array([1,2,3,4])
np.sum(x)

10

In [36]:
#Sum by rows and by columns
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [37]:
x.sum(axis=0)  #columns first dimension

array([3, 3])

In [38]:
x.sum(axis=1) # rows(second dimension)

array([2, 4])

### Other Reductions

In [39]:
x = np.array([1, 3, 2])
x.min()

1

In [40]:
x.max()

3

In [41]:
x.argmin() #index of minimum element

0

In [42]:
x.argmax() # index of maximum element

1

### Statistics

In [43]:
normal_array = np.arange(0,10,1)
print('Array is ',format(normal_array))

### min
print('min element is ',np.min(normal_array))

### max
print('max element is',np.max(normal_array))

### Sum
print('sum of elements in array is',np.sum(normal_array))

### Mean
print('mean of elements in array is',np.mean(normal_array))

### Median
print('median of elements in array is',np.median(normal_array))

### Sd
print('standard deviation of elements in array is',np.std(normal_array))

Array is  [0 1 2 3 4 5 6 7 8 9]
min element is  0
max element is 9
sum of elements in array is 45
mean of elements in array is 4.5
median of elements in array is 4.5
standard deviation of elements in array is 2.8722813232690143
